### ISSUE TITLE
Prof. Luis Grim IFSP - testando seu projeto.

### ISSUE THREAD

**Issue by lfgrim** [aldemirneto/real-estate-web#1]
Boa tarde Aldemir, tudo bom?

Estava testando seu projeto e de repente parou de funcionar. 

Se puder habilitar novamente para eu poder fazer mais alguns testes eu agradeço. 

Bom final de expediente e nos vemos amanhã no seu TCC.

Prof. Luís Grim - IFSP

**Comment by aldemirneto** [comment]
Bom dia professor! desculpe a demora em responder, qual parte exatamente parou de funcionar?

**Comment by lfgrim** [comment]
Bom dia!
Tranquilo Aldemir,
Na ocasião ele havia parado totalmente, mostrado apenas uma mensagem de erro com o contato do suporte, que foi por onde lhe enviei a mensagem.
No entanto, mais tarde consegui acessar normalmente de casa, e agora testei novamente aqui do IFSP e voltou a funcionar também. Me parece que ocorreu alguma indisponibilidade temporária em algum dos serviços que você utiliza.
Já realizei os testes que gostaria, consegui utilizar a plataforma mas achei alguns bugs também, que eu comento na sua apresentação hoje a tarde. Se não for possível te envio um e-mail depois.

Att.
Prof. Luís Grim

    Em quarta-feira, 25 de setembro de 2024 às 08:29:45 BRT, Aldemir Humberto Soares Neto ***@***.***> escreveu:  
 
 


Bom dia professor! desculpe a demora em responder, qual parte exatamente parou de funcionar?
